 # Topic02: Remove HTML Tags

In [12]:
html_text = "<html><body><h1>Hello</h1><p>Text</p></body></html>"
print(f'HTML TAGS = {html_text}')

HTML TAGS = <html><body><h1>Hello</h1><p>Text</p></body></html>

In [15]:
'''(module) re
Support for regular expressions (RE).

This module provides regular expression matching operations similar to
those found in Perl. It supports both 8-bit and Unicode strings; both
the pattern and the strings being processed can contain null bytes and
characters outside the US ASCII range.

Regular expressions can contain both special and ordinary characters.
Most ordinary characters, like "A", "a", or "0", are the simplest
regular expressions; they simply match themselves. You can
concatenate ordinary characters, so last matches the string 'last'.'''

import re
def remove_html_tags(html_text):

    pattern = re.compile('<.*?>')
    return pattern.sub(r'' , html_text)

print('Without HTML TAGS:')
remove_html_tags(html_text)

Without HTML TAGS:

'HelloText'

In [16]:
import pandas as pd

In [ ]:
df = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\NLP\Text_Preprocessing\IMDB Dataset.csv.zip')
df.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

# Remove HTML Tags From DataFrame

In [23]:
df['review'] = df['review'].apply(remove_html_tags)

print('Remove HTML Tags from DataFrame:')
df

Remove HTML Tags from DataFrame:

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]