# Topic: Remove Punctuation

In [14]:
import string , time

In [15]:
punct = string.punctuation
print(f'Punctuation: {punct}') #Python Concider Punctuation

Punctuation: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

### This Technique Apply Very Small DataSet

In [16]:
exclude = punct
text = 'One + Day. I, am a. successfull! person-'

def remove_punct(text):

    for char in exclude:
        
       text = text.replace(char , '')
    
    return text    

start = time.time()    
print(remove_punct(text))
time1 = time.time() - start

print(f'Time Consume is:{time1}Sec if 1 Row')
print(f'\nTime Consume is:{time1*50000}Sec if 50000 Rows')
print(f'\nTime Consume is:{time1*100000}Sec if 100000 Rows')

One  Day I am a successfull person
Time Consume is:0.0005962848663330078Sec if 1 Row

Time Consume is:29.81424331665039Sec if 50000 Rows

Time Consume is:59.62848663330078Sec if 100000 Rows

In [17]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\NLP\tweets.csv')
df.head()

   ItemID  Sentiment SentimentSource                      SentimentText
0    1038          1    Sentiment140  that film is fantastic #brilliant
1    1804          1    Sentiment140   this music is really bad #myband
2    1693          0    Sentiment140    winter is terrible #thumbs-down
3    1477          0    Sentiment140      this game is awful #nightmare
4      45          1    Sentiment140                 I love jam #loveit

In [18]:
df.shape

(1932, 4)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1932 entries, 0 to 1931
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ItemID           1932 non-null   int64
 1   Sentiment        1932 non-null   int64
 2   SentimentSource  1932 non-null   object
 3   SentimentText    1932 non-null   object
dtypes: int64(2), object(2)
memory usage: 60.5+ KB

In [20]:
df.isnull().sum()

ItemID             0
Sentiment          0
SentimentSource    0
SentimentText      0
dtype: int64

In [21]:
df.sample(5)

      ItemID  Sentiment SentimentSource                       SentimentText
1797    1904          1    Sentiment140  rock music is brilliant #toptastic
1546    1455          1    Sentiment140    that movie is the best #favorite
1695     818          1    Sentiment140           I adore summer #toptastic
1363    1313          1    Sentiment140    this book is fantastic #bestever
127      280          0    Sentiment140         I hate this team #worstever

### This Technique Apply Big DataSet

In [24]:
import string 

punctua = string.punctuation
exclude = punctua
print(exclude)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [30]:
def remove_punct(text):
    return text.translate(str.maketrans('','',exclude))

# start = time.time()
df['SentimentText'] = df['SentimentText'].apply(remove_punct)
df
# time2 = time.time() - start

# print(f'{time2}')
# print(f'\nTime Consume is:{time2*50000}Sec if 50000 Rows')
# print(f'\nTime Consume is:{time2*100000}Sec if 100000 Rows')
# print(f'\n{time1/time2}')

      ItemID  Sentiment SentimentSource                          SentimentText
0       1038          1    Sentiment140       that film is fantastic brilliant
1       1804          1    Sentiment140        this music is really bad myband
2       1693          0    Sentiment140          winter is terrible thumbsdown
3       1477          0    Sentiment140           this game is awful nightmare
4         45          1    Sentiment140                      I love jam loveit
...      ...        ...             ...                                    ...
1927       4          1    Sentiment140                I like this team loveit
1928    1717          0    Sentiment140  the holidays is really bad thumbsdown
1929    1792          0    Sentiment140             that band is terrible fail
1930    1521          0    Sentiment140      that film is really bad nightmare
1931     861          1    Sentiment140          this game is fantastic loveit

[1932 rows x 4 columns]